version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - GOOGLE_API_HOST=${GOOGLE_API_HOST}
      - DATABASE_URL=file:/app/data/dev.db
    volumes:
      # Mount a data volume to persist the SQLite database
      - ./data:/app/data
